<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tyto</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>Tyto</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#metadata</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#marker-head-arguments-multiline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#marker-head-arguments</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>marker-head-arguments</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.block.tyto</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#dictionary</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\[a-zA-Z\-]+)(\[.*\])?(?=\{\s*(?:##.*)?$)</string>
				</dict>
				<key>marker-head-arguments-multiline</key>
				<dict>
					<key>begin</key>
					<string>(\\[a-zA-Z\-]+)(\[)(?=\s*(?:##.*)?$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.block.tyto</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.tyto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\])?(?=\{\s*(?:##.*)?$)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.tyto</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#dictionary-body</string>
						</dict>
					</array>
				</dict>
				<key>metadata</key>
				<dict>
					<key>begin</key>
					<string>\A\s*\[</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#dictionary-body</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>boolean</key>
		<dict>
			<key>match</key>
			<string>\.(?:true|false)\b</string>
			<key>name</key>
			<string>constant.language.boolean.tyto</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>##.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.tyto</string>
		</dict>
		<key>date</key>
		<dict>
			<key>match</key>
			<string>[+-]?[0-9]{4,}-[0-1][0-9]-[0-3][0-9](?:[T ][0-2][0-9]:[0-5][0-9]:[0-5][0-9](?:\.[0-9]+)?)?(?:[+-][0-2][0-9](?::[0-5][0-9])?|Z)?</string>
			<key>name</key>
			<string>constant.other.date.tyto</string>
		</dict>
		<key>dictionary</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.begin.tyto</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.end.tyto</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.dictionary.tyto</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dictionary-body</string>
				</dict>
			</array>
		</dict>
		<key>dictionary-body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dictionary-key</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
			</array>
		</dict>
		<key>dictionary-key</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.argument.tyto</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.tyto</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z\-]+)(:)</string>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>[^\s,].*</string>
			<key>name</key>
			<string>invalid.illegal.tyto</string>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#marker-head-arguments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#marker-head</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-raw</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>marker-head</key>
				<dict>
					<key>match</key>
					<string>\\[a-zA-Z\-]+</string>
					<key>name</key>
					<string>support.function.marker.tyto</string>
				</dict>
				<key>marker-head-arguments</key>
				<dict>
					<key>begin</key>
					<string>(\\[a-zA-Z\-]+)(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.marker.tyto</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.tyto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.tyto</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#dictionary-body</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>list</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.begin.tyto</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.tyto</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.array.list.tyto</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#base10-float</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#base10-int</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>base10-float</key>
				<dict>
					<key>match</key>
					<string>\b(?:0|[+\-]?[1-9](_?[0-9])*)\.(?:[0-9]|([0-9]_?)+[1-9])\b</string>
					<key>name</key>
					<string>constant.numeric.float.tyto</string>
				</dict>
				<key>base10-int</key>
				<dict>
					<key>match</key>
					<string>\b(?:0|[+\-]?[1-9](_?[0-9])*)\b</string>
					<key>name</key>
					<string>constant.numeric.integer.decimal.tyto</string>
				</dict>
			</dict>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#triple</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>single</key>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.tyto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.tyto</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.tyto</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-escape-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-escape-unicode</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-escape-symbol</string>
						</dict>
					</array>
				</dict>
				<key>string-escape-single</key>
				<dict>
					<key>match</key>
					<string>\\"</string>
					<key>name</key>
					<string>constant.character.escape.symbol.tyto</string>
				</dict>
				<key>string-escape-symbol</key>
				<dict>
					<key>match</key>
					<string>\\[\\nr]</string>
					<key>name</key>
					<string>constant.character.escape.symbol.tyto</string>
				</dict>
				<key>string-escape-triple</key>
				<dict>
					<key>match</key>
					<string>\\"""</string>
					<key>name</key>
					<string>constant.character.escape.symbol.tyto</string>
				</dict>
				<key>string-escape-unicode</key>
				<dict>
					<key>match</key>
					<string>\\u\{[0-9A-F]+\}</string>
					<key>name</key>
					<string>constant.character.escape.unicode.tyto</string>
				</dict>
				<key>triple</key>
				<dict>
					<key>begin</key>
					<string>"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.tyto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.tyto</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.triple.tyto</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-escape-triple</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-escape-unicode</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-escape-symbol</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>string-raw</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#triple</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>single</key>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.tyto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>`</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.tyto</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.grave-accent.tyto</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-raw-escape-single</string>
						</dict>
					</array>
				</dict>
				<key>string-raw-escape-single</key>
				<dict>
					<key>match</key>
					<string>\\`</string>
					<key>name</key>
					<string>constant.character.escape.symbol.tyto</string>
				</dict>
				<key>string-raw-escape-triple</key>
				<dict>
					<key>match</key>
					<string>\\```</string>
					<key>name</key>
					<string>constant.character.escape.symbol.tyto</string>
				</dict>
				<key>triple</key>
				<dict>
					<key>begin</key>
					<string>```</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.tyto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>```</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.tyto</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.grave-accent.triple.tyto</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-raw-escape-triple</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>tagged-union</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagged-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>tag</key>
				<dict>
					<key>match</key>
					<string>\.[a-zA-Z\-]+</string>
					<key>name</key>
					<string>constant.other.symbol.tagged-union.tag.tyto</string>
				</dict>
				<key>tagged-list</key>
				<dict>
					<key>begin</key>
					<string>(\.[a-zA-Z\-]+)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.symbol.tagged-union.tag.tyto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>name</key>
					<string>meta.structure.tagged-union.tyto</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#values</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>text</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text-frame</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>text-escape-symbol</key>
				<dict>
					<key>match</key>
					<string>\\[\\{}\[\]`]</string>
					<key>name</key>
					<string>constant.character.escape.symbol.tyto</string>
				</dict>
				<key>text-frame</key>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.tyto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.tyto</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block.text.tyto</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#text-escape-symbol</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dictionary</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tagged-union</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.tyto</string>
	<key>uuid</key>
	<string>EC9B0614-0189-42F8-85F9-F6114F60A180</string>
</dict>
</plist>
